INSERT INTO item (nome, tipo_item, preco, descricao)
VALUES
    ('Potion', 'Cura', 200, 'Heals a Pokémon by 20 HP.'),
    ('Super Potion', 'Cura', 700, 'Heals a Pokémon by 50 HP.'),
    ('Hyper Potion', 'Cura', 1200, 'Heals a Pokémon by 200 HP.'),
    ('Max Potion', 'Cura', 2500, 'Fully restores the HP of a Pokémon.'),
    ('Full Restore', 'Cura', 3000, 'Fully restores a Pokémon''s HP and removes any status conditions.'),
    ('Revive', 'Revive', 1500, 'Revives a fainted Pokémon and restores half of its max HP.'),
    ('Max Revive', 'Revive', 4000, 'Fully revives a fainted Pokémon.'),
    ('Antidote', 'Status', 100, 'Heals a poisoned Pokémon.'),
    ('Burn Heal', 'Status', 250, 'Heals a Pokémon from a burn condition.'),
    ('Ice Heal', 'Status', 250, 'Heals a Pokémon from a freeze condition.'),
    ('Awakening', 'Status', 200, 'Awakens a sleeping Pokémon.'),
    ('Parlyz Heal', 'Status', 200, 'Heals a paralyzed Pokémon.'),
    ('Full Heal', 'Status', 600, 'Heals a Pokémon from any status conditions.'),
    ('Escape Rope', 'Recuperação', 550, 'Allows the player to escape from caves and dungeons.'),
    ('Repel', 'Outro', 350, 'Prevents wild Pokémon from appearing for 100 steps.'),
    ('Super Repel', 'Outro', 500, 'Prevents wild Pokémon from appearing for 200 steps.'),
    ('Max Repel', 'Outro', 700, 'Prevents wild Pokémon from appearing for 250 steps.'),
    ('X Attack', 'Aumento de Stats', 500, 'Raises the Attack stat during battle.'),
    ('X Defense', 'Aumento de Stats', 550, 'Raises the Defense stat during battle.'),
    ('X Speed', 'Aumento de Stats', 350, 'Raises the Speed stat during battle.'),
    ('X Special Attack', 'Aumento de Stats', 350, 'Raises the Special Attack stat during battle.'),
    ('X Special Defense', 'Aumento de Stats', 400, 'Raises the Special Defense stat during battle.'),
    ('X Accuracy', 'Aumento de Stats', 450, 'Raises the Accuracy stat during battle.'),
    ('Dire Hit', 'Aumento de Stats', 650, 'Raises the critical-hit ratio during battle.'),
    ('Guard Spec.', 'Aumento de Stats', 700, 'Prevents stat reduction among the trainer''s party for five turns.'),
    ('Poke Ball', 'Bola', 200, 'A device for catching and holding Pokémon.'),
    ('Great Ball', 'Bola', 600, 'A good, high-performance Ball to catch Pokémon.'),
    ('Ultra Ball', 'Bola', 1200, 'An ultra-high-performance Ball to catch Pokémon.'),
    ('Master Ball', 'Bola', 10000, 'The best Ball with the ultimate performance.'),
    ('Safari Ball', 'Bola', 500, 'A special Poké Ball for use in the Safari Zone.'),
    ('Net Ball', 'Bola', 1000, 'A somewhat different Ball that works especially well on Water- and Bug-type Pokémon.'),
    ('Dive Ball', 'Bola', 1000, 'A somewhat different Ball that works especially well on Pokémon that live underwater.'),
    ('Nest Ball', 'Bola', 500, 'A somewhat different Ball that works especially well on weaker Pokémon in the wild.'),
    ('Repeat Ball', 'Bola', 1000, 'A somewhat different Ball that works especially well on Pokémon species that were caught before.'),
    ('Timer Ball', 'Bola', 1000, 'A somewhat different Ball that becomes progressively more effective the more turns are taken in battle.'),
    ('Luxury Ball', 'Bola', 1000, 'A comfortable Poké Ball that makes a caught wild Pokémon quickly grow friendly.'),
    ('Premier Ball', 'Bola', 200, 'A somewhat rare Poké Ball that was made as a commemorative item used to celebrate an event of some sort.'),
    ('Bicycle', 'Outro', 1000, 'Allows the player to travel faster.'),
    ('Old Rod', 'Outro', 50, 'A simple fishing rod. Use it by any body of water to fish for wild aquatic Pokémon.'),
    ('Good Rod', 'Outro', 150, 'A good, sturdy fishing rod. Use it by any body of water to fish for wild aquatic Pokémon.'),
    ('Super Rod', 'Outro', 500, 'An awesome, high-tech fishing rod. Use it by any body of water to fish for wild aquatic Pokémon.');